# Generated by Django 4.2.6 on 2023-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='coverpath',
        ),
        migrations.AddField(
            model_name='game',
            name='coverart',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
