# Generated by Django 4.2.6 on 2023-10-29 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0002_remove_game_coverpath_game_coverart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars'), (6, '6 Stars'), (7, '7 Stars'), (8, '8 Stars'), (9, '9 Stars'), (10, '10 Stars')])),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='switched_app.game')),
            ],
        ),
    ]
