# Generated by Django 4.2.6 on 2023-11-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0004_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='heading',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='img_src',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='coverart',
            field=models.ImageField(blank=True, default='images/default.gif', upload_to='images/'),
        ),
    ]
