# Generated by Django 4.2.6 on 2023-11-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0004_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='coverart',
            field=models.ImageField(blank=True, default='images/default.gif', upload_to='images/'),
        ),
    ]
