# Generated by Django 4.2.9 on 2024-01-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0005_alter_game_coverart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='coverart',
            field=models.ImageField(blank=True, default='images/default.gif', null=True, upload_to='images/'),
        ),
    ]
