# Generated by Django 4.2.6 on 2023-12-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0005_game_heading_game_img_src_game_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='img_src',
        ),
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='coverart',
            field=models.ImageField(blank=True, default='images/default.gif', null=True, upload_to='images/'),
        ),
    ]
