# Generated by Django 4.2.9 on 2024-01-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0006_alter_game_coverart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='coverart',
        ),
        migrations.AddField(
            model_name='game',
            name='heading',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
