# Generated by Django 4.2.9 on 2024-01-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0007_remove_game_coverart_game_heading_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='heading',
            field=models.CharField(max_length=50),
        ),
    ]
