# Generated by Django 4.2.9 on 2024-01-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switched_app', '0007_game_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_url',
            field=models.URLField(),
        ),
    ]
